; [platformio]
; 获取当前目录的绝对路径
; default_envs = app
; platformio.ini - 统一管理 app 和 boot 两个工程
; 公共配置部分，所有环境共享
[common]
platform = ststm32
; 目标开发板
board = genericSTM32F401RE
; mcu型号
board_build.mcu = stm32f401retx
; 设置CPU频率
board_build.f_cpu = 84000000L
; 定义外部晶振频率为8MHz
build_flags = 
    -D HSE_VALUE=8000000 
    -Wl,-u,_printf_float
; 使用STM32Cube框架
framework = stm32cube
; 烧写方式
upload_protocol = stlink
; upload_protocol = cmsis-dap
; 调试方式
debug_tool = stlink 

; ===== app 工程配置 =====
[env:app]
extends = common
; 使用 build_src_filter 指定源文件路径
build_src_filter = 
    +<${PROJECT_DIR}/app/src/>
    +<${PROJECT_DIR}/app/lib/>
    -<${PROJECT_DIR}/bootloader/>
; 头文件搜索路径
build_flags = 
    ${common.build_flags}
    -I${PROJECT_DIR}/app/include
    -I${PROJECT_DIR}/app/src
    -Wl,-Map,${PROJECT_DIR}/output/app.map  ; 生成map文件到指定目录
; 使用自定义链接脚本
board_build.ldscript = ${PROJECT_DIR}/app/STM32F401RETX_FLASH_CUSTOM.ld
; 指定输出文件名，避免与 boot 冲突
board_build.name = app_firmware
; 禁用库文件归档
lib_archive = no
; 库依赖
lib_deps = 
; 自定义脚本
extra_scripts = 
    pre:app/export_clangd.py
    post:app/export_hex.py

; ===== bootloader 工程配置 =====
[env:bootloader]
extends = common
; 使用 build_src_filter 指定源文件路径
build_src_filter = 
    +<${PROJECT_DIR}/bootloader/src/>
    +<${PROJECT_DIR}/bootloader/lib/>
    -<${PROJECT_DIR}/app/>
; 头文件搜索路径
build_flags = 
    ${common.build_flags}
    -I${PROJECT_DIR}/app/include
    -I${PROJECT_DIR}/app/src
    -Wl,-Map,${PROJECT_DIR}/output/bootloader.map  ; 生成map文件到指定目录
; 使用自定义链接脚本
board_build.ldscript = ${PROJECT_DIR}/bootloader/STM32F401RETX_FLASH_CUSTOM.ld
; 指定输出文件名，避免与 boot 冲突
board_build.name = bootloader_firmware
; 禁用库文件归档
lib_archive = no
; 库依赖
lib_deps = 
; 自定义脚本
extra_scripts = 
    pre:bootloader/export_clangd.py
    post:bootloader/export_hex.py