; [platformio]
; 获取当前目录的绝对路径
; default_envs = app
; platformio.ini - 统一管理 app 和 boot 两个工程
; 公共配置部分，所有环境共享
[common]
platform = ststm32
; 目标开发板
board = genericSTM32F401RE
; mcu型号
board_build.mcu = stm32f401retx
; 设置CPU频率
board_build.f_cpu = 84000000L
; 手动指定 stm32f4xx_hal_conf.h，防止编译出的固件太大
board_build.stm32cube.custom_config_header = yes
; 定义外部晶振频率为8MHz
build_flags = 
    -D HSE_VALUE=8000000 
    -Wl,-u,_printf_float
; 使用STM32Cube框架
framework = stm32cube
; 烧写方式
upload_protocol = stlink
; upload_protocol = cmsis-dap
; 调试方式
debug_tool = stlink 

; ================================= app1 工程配置 =================================
[env:app1]
extends = common
; 使用 build_src_filter 指定源文件路径
build_src_filter = 
    +<${PROJECT_DIR}/app1/src/>
    -<${PROJECT_DIR}/bootloader/>
    -<${PROJECT_DIR}/app2/>
; 头文件搜索路径
build_flags = 
    ${common.build_flags}
    -I${PROJECT_DIR}/app1/include
    -I${PROJECT_DIR}/app1/src
    -Wl,-Map,${PROJECT_DIR}/output/app1.map  ; 生成map文件到指定目录
; 使用自定义链接脚本
board_build.ldscript = ${PROJECT_DIR}/app1/STM32F401RETX_FLASH_CUSTOM.ld
; 指定输出文件名，避免与 boot 冲突
board_build.name = app1_firmware
; 禁用库文件归档
lib_archive = no
; 库依赖
lib_deps = 
; 自定义脚本
extra_scripts = 
    pre:app1/export_clangd.py
    post:app1/export_hex.py

; ================================= app2 工程配置 =================================
[env:app2]
extends = common
; 使用 build_src_filter 指定源文件路径
build_src_filter = 
    +<${PROJECT_DIR}/app2/src/>
    -<${PROJECT_DIR}/bootloader/>
    -<${PROJECT_DIR}/app1/>
; 头文件搜索路径
build_flags = 
    ${common.build_flags}
    -I${PROJECT_DIR}/app2/include
    -I${PROJECT_DIR}/app2/src
    -Wl,-Map,${PROJECT_DIR}/output/app2.map  ; 生成map文件到指定目录
; 使用自定义链接脚本
board_build.ldscript = ${PROJECT_DIR}/app2/STM32F401RETX_FLASH_CUSTOM.ld
; 指定输出文件名，避免与 boot 冲突
board_build.name = app2_firmware
; 禁用库文件归档
lib_archive = no
; 库依赖
lib_deps = 
; 自定义脚本
extra_scripts = 
    pre:app2/export_clangd.py
    post:app2/export_hex.py

; ================================= bootloader 工程配置 =================================
[env:bootloader]
extends = common
; 使用 build_src_filter 指定源文件路径
build_src_filter = 
    +<${PROJECT_DIR}/bootloader/src/>
    -<${PROJECT_DIR}/app1/>
    -<${PROJECT_DIR}/app2/>
; 头文件搜索路径
build_flags = 
    ${common.build_flags}
    -I${PROJECT_DIR}/bootloader/include
    -I${PROJECT_DIR}/bootloader/src
    -Wl,-Map,${PROJECT_DIR}/output/bootloader.map  ; 生成map文件到指定目录

; 使用自定义链接脚本
board_build.ldscript = ${PROJECT_DIR}/bootloader/STM32F401RETX_FLASH_CUSTOM.ld
; 指定输出文件名，避免与 boot 冲突
board_build.name = bootloader_firmware
; 禁用库文件归档
lib_archive = no
; 库依赖
lib_deps = 
    file://${PROJECT_DIR}/bootloader/lib/debug
    file://${PROJECT_DIR}/bootloader/lib/ymodem
; 自定义脚本
extra_scripts = 
    pre:bootloader/export_clangd.py
    post:bootloader/export_hex.py
